### PR TITLE
Add basic Rust security rules

### PR DESCRIPTION
**Pull request by rc-mattschwager**
Hi all,

I'd like to contribute to bumping Rust from experimental -> beta (https://github.com/returntocorp/semgrep/issues/6545). Having some basic Rust rules is a prerequisite to that. These look like the first Rust rules, so I think this is a good start on basic security rules.

The `std` library rules come from searching the docs for "security" and "warning." The rest come from basic security ideas that apply to most languages/libraries.

### CODE REVIEW

**Comment by 0xDC0DE** [comment]
Hi @rc-mattschwager ! Thanks for your contribution!! 

We had some trouble with our CI checks, but these should be fixed. If you can merge our develop branch into yours, the CI checks should run successfully and we can continue reviewing your contribution.

**Comment by rc-mattschwager** [comment]
> Hi @rc-mattschwager ! Thanks for your contribution!!
> 
> We had some trouble with our CI checks, but these should be fixed. If you can merge our develop branch into yours, the CI checks should run successfully and we can continue reviewing your contribution.

Hey @0xDC0DE, I've rebased on the latest `develop` 👍

**Comment by 0xDC0DE** [comment]
Perfect! It looks like you are missing a bunch of metadata. We've recently been working to get our metadata to a higher standard. You can read some more about this in the docs [here](https://semgrep.dev/docs/contributing/contributing-to-semgrep-rules-repository/#including-fields-required-by-security-category).

There will be more CI checks coming soon to verify use of these metadata fields, but we are still working on getting that merged: https://github.com/returntocorp/semgrep-rules/pull/2505

Sorry for the inconvenience!

**Comment by rc-mattschwager** [comment]
> Perfect! It looks like you are missing a bunch of metadata. We've recently been working to get our metadata to a higher standard. You can read some more about this in the docs [here](https://semgrep.dev/docs/contributing/contributing-to-semgrep-rules-repository/#including-fields-required-by-security-category).
> 
> There will be more CI checks coming soon to verify use of these metadata fields, but we are still working on getting that merged: #2505
> 
> Sorry for the inconvenience!

Done 👍

**Comment by 0xDC0DE** [comment]
Great! Almost there, the rule-lints suggest to use `message: >-`, not `message: |` in the messages of rules as this will display multi-line messages better in the terminal.

I've read through the rule messages and patterns and everything else looks good to me!

**Comment by rc-mattschwager** [comment]
> Use YAML >- instead of |

Fixed in https://github.com/returntocorp/semgrep-rules/pull/2568/commits/71f69a1e35b798d1b58454577f0e137a6439987f

**Comment by rc-mattschwager** [comment]
Hey @0xDC0DE can we get this over the line today? It's been open for over two weeks now.

Red Canary has signed the org-wide CLA, so I think we should be good to go on that front, although it's not showing in the CLA check. And I believe the test failures in CI were unrelated to the changes made in this PR.

**Review by p4p3r — APPROVED** [review]
LGTM

**Comment by rc-mattschwager** [comment]
Closing and re-opening a new PR to retry CLA process...

**Pull request closed without merging**
